import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TodoList",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#4285f4" />
        <link rel="manifest" href="/manifest.json" /> 
      <title>TodoList Anurag</title>
    </head>
      <body className={inter.className}>{children}</body>
    </html>
    
  );
}
